services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: usuariosimse
      POSTGRES_PASSWORD: th1s@p4ssw0rd
      POSTGRES_DB: bd_simse
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres/data:/var/lib/postgresql/data

